import test from 'node:test';import assert from 'node:assert/strict';import {stockedState} from './helpers/kitchen.mjs';import {cookingPlan} from '../src/domain.js';import {renderTutorialComponents,tutorialComponentModel,tutorialStateAsset} from '../src/tutorial-components.js';import {displayQty} from '../src/food-rules.js';
test('standard and time-saving plans render identical component structure with every instruction retained',()=>{for(const prefs of [[],['省时间']]){const s=stockedState();s.meal.selectedRecipeIds=['tomato_pasta','miso_tofu_soup'];s.meal.constraints.operationPrefs=prefs;const plan=cookingPlan(s),before=JSON.stringify(plan),html=renderTutorialComponents(plan,{diners:2,quantityLabel:i=>displayQty(s,i.ingredientId,i.qty)}),model=tutorialComponentModel(plan);assert.equal(model.prep.length+model.cooking.length,plan.atomicTimeline.length);for(const step of plan.atomicTimeline)assert.ok(html.includes(step.instruction),step.id);for(const cls of ['tutorial-dish-hero','tutorial-preparation','tutorial-prep-cards','tutorial-timeline','tutorial-finish','tutorial-finish-actions'])assert.ok(html.includes(cls));assert.equal(JSON.stringify(plan),before);assert.ok(!html.includes('visual-composition'));assert.ok(!html.includes('chapter-aside'));}});
test('state matching never puts a raw preparation image into a heated step',()=>{assert.equal(tutorialStateAsset({phase:'heat',ingredientIds:['tomato'],instruction:'番茄切块后炒熟'}),null);assert.match(tutorialStateAsset({phase:'prep',ingredientIds:['tomato'],instruction:'番茄切块'}),/tomato_chunks/);assert.equal(tutorialStateAsset({phase:'prep',ingredientIds:['tofu'],instruction:'豆腐切块'}),null);});
test('preparation groups repeated instructions without removing safety instructions or mutating the schedule',async()=>{
 const {preparationGroups}=await import('../src/tutorial-components.js');
 const plan={adaptedRecipes:[{id:'a',name:'番茄炒蛋'}],atomicTimeline:[
 {id:'a/wash',recipeId:'a',phase:'wash',start:0,end:1,instruction:'洗净番茄',ingredientIds:['tomato']},
 {id:'a/prep',recipeId:'a',phase:'prep',start:1,end:3,instruction:'番茄切块，鸡蛋打散。',ingredientIds:['tomato','egg']},
 {id:'a/duplicate',recipeId:'a',phase:'prep',start:3,end:4,instruction:'番茄切块，鸡蛋打散。',ingredientIds:['tomato','egg']},
 {id:'a/safety',recipeId:'a',phase:'prep',start:4,end:5,instruction:'处理后洗手。',ingredientIds:[]}]};
 const before=JSON.stringify(plan),groups=preparationGroups(plan);assert.equal(groups.length,1);assert.equal(groups[0].steps.length,4);assert.equal(groups[0].instructions.length,3);assert.ok(groups[0].instructions.includes('处理后洗手。'));assert.equal(JSON.stringify(plan),before);
});
