import {recipes,ingredients} from './data.js';
import {eligible,requirements,totalStock,shortages,cookingPlan,validateCookingPlan} from './domain.js';
export class MockAdapter {
 async planBasket(state){const anchors=state.cycle.anchorWantedDishIds.map(id=>state.wanted.find(w=>w.id===id)?.linkedRecipeId).filter(Boolean);const valid=recipes.filter(r=>eligible(r,state));const blocked=anchors.filter(id=>!valid.some(r=>r.id===id));if(blocked.length)throw new Error('所选锚点菜与厨房或饮食限制冲突，请保留意愿并调整本轮选择');const ranked=[...valid].sort((a,b)=>Number(anchors.includes(b.id))-Number(anchors.includes(a.id))||Number(state.cycle.styles.includes(b.cuisine))-Number(state.cycle.styles.includes(a.cuisine)));if(!ranked.length)throw new Error('当前菜谱库没有符合厨房与饮食限制的方案');const preferred=ranked.filter(r=>state.cycle.styles.includes(r.cuisine));const pool=(preferred.length?preferred:ranked).slice(0,4);if(state.cycle.habits.includes('20分钟内'))pool.sort((a,b)=>a.totalTime-b.totalTime);const referenceRecipeIds=[...anchors];for(let n=referenceRecipeIds.length;n<state.cycle.expectedMeals*2;n++)referenceRecipeIds.push(pool[n%pool.length].id);const ingredientSuggestions=requirements(referenceRecipeIds,state.profile.defaultDiners).map(i=>({ingredientId:i.ingredientId,requiredQty:i.qty,existingQty:state.cycle.carryOverEnabled?totalStock(state,i.ingredientId):0,purchaseQty:Math.max(0,i.qty-(state.cycle.carryOverEnabled?totalStock(state,i.ingredientId):0)),unit:i.unit,reasonCodes:[totalStock(state,i.ingredientId)>0?'承接现有库存':'本轮菜品共享食材'],locked:false}));return {referenceRecipeIds,ingredientSuggestions,tradeoffs:[...(new Set(referenceRecipeIds).size>3?['本轮食材种类较多，可减少风格或锚点菜以缩小采购量。']:[]),...state.cycle.styles.filter(s=>s!=='还没想好'&&!valid.some(r=>r.cuisine===s)).map(s=>`${s}暂不在示例菜谱库内，本轮使用其他已验证菜谱。`)]};}
 async recommendRecipes(state){return {recipeCards:recipes.filter(r=>eligible(r,state)).map(r=>{const missing=shortages(state,requirements([r.id],state.meal.diners));const match=state.meal.constraints.mealType==='还没想好'||state.meal.constraints.mealType===r.subtype;return {recipeId:r.id,canCookNow:missing.length===0,missingIngredients:missing,reasonCodes:[],shortReason:missing.length?`还缺 ${missing.length} 种食材`:'现有食材可做',score:(missing.length?-(state.meal.constraints.stockPolicy==='现有食材优先'?10:3)*missing.length:20)+(match?8:0)+(r.totalTime<=state.meal.constraints.timeLimit?3:-10)+(state.cycle.styles.includes(r.cuisine)?2:0)+(state.cycle.anchorWantedDishIds.some(id=>state.wanted.find(w=>w.id===id)?.linkedRecipeId===r.id)?3:0)-(state.records.slice(0,3).some(x=>x.recipeIds?.includes(r.id))?2:0)};}).sort((a,b)=>b.score-a.score)};}
 async generateCookingPlan(state){return cookingPlan(state);}
 async parseReceiptOrIngredientPhoto(){return {items:[{ingredientIdCandidate:'tomato',nameCandidate:'番茄',qtyCandidate:2,unitCandidate:'个',confidence:0.5}]};}
 async parseDishPhoto(){return {dishNameCandidates:['番茄炒蛋'],styleTags:['家常'],linkedRecipeCandidates:['tomato_scrambled_egg']};}
 async parseKitchenPhoto(){return {toolCandidates:[{type:'wok',name:'炒锅',quantityCandidate:1,confidence:0.5},{type:'stockpot',name:'汤锅',quantityCandidate:1,confidence:0.5}],stoveSlotsCandidate:2};}
}
// Backend handles credentials. The browser only posts task context to a same-origin endpoint.
export class RealAIAdapter {
 constructor(endpoint='/api/ai'){this.endpoint=endpoint;}
 async request(task,input){const response=await fetch(this.endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task,input}),signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error('AI 服务暂不可用，请稍后重试');return response.json();}
}
for(const task of ['planBasket','recommendRecipes','generateCookingPlan','parseReceiptOrIngredientPhoto','parseDishPhoto','parseKitchenPhoto'])RealAIAdapter.prototype[task]=function(input){return this.request(task,input);};
export class AIService {
 constructor(adapter=new MockAdapter()){this.adapter=adapter;this.mode=adapter instanceof MockAdapter?'Mock':'Real';}
 async planBasket(state){const out=await this.adapter.planBasket(structuredClone(state));if(!Array.isArray(out.referenceRecipeIds)||!out.referenceRecipeIds.length||out.referenceRecipeIds.some(id=>!recipes.some(r=>r.id===id&&eligible(r,state))))throw new Error('AI 方案未通过菜谱校验');const anchors=state.cycle.anchorWantedDishIds.map(id=>state.wanted.find(w=>w.id===id)?.linkedRecipeId).filter(Boolean);if(anchors.some(id=>!out.referenceRecipeIds.includes(id)))throw new Error('AI 方案遗漏了锚点菜');const rows=requirements(out.referenceRecipeIds,state.profile.defaultDiners).map(i=>{const existingQty=state.cycle.carryOverEnabled?totalStock(state,i.ingredientId):0;return {ingredientId:i.ingredientId,requiredQty:i.qty,existingQty,purchaseQty:Math.max(0,i.qty-existingQty),unit:i.unit,reasonCodes:[existingQty?'优先用已有食材':'来自本轮参考菜品'],locked:false};});return {...out,ingredientSuggestions:rows,tradeoffs:Array.isArray(out.tradeoffs)?out.tradeoffs.filter(x=>typeof x==='string'):[]};}
 async recommendRecipes(state){const out=await this.adapter.recommendRecipes(structuredClone(state));if(!Array.isArray(out.recipeCards))throw new Error('推荐格式无效');return {recipeCards:out.recipeCards.filter(c=>recipes.some(r=>r.id===c.recipeId&&eligible(r,state))).map(c=>{const missing=shortages(state,requirements([c.recipeId],state.meal.diners));return {...c,canCookNow:!missing.length,missingIngredients:missing,shortReason:missing.length?`还缺 ${missing.length} 种食材`:'现有食材可做'};})};}
 async generateCookingPlan(state){const plan=await this.adapter.generateCookingPlan(structuredClone(state));return validateCookingPlan(plan,state);}
 async parseReceiptOrIngredientPhoto(image){const out=await this.adapter.parseReceiptOrIngredientPhoto(image);if(!Array.isArray(out.items))throw new Error('识别格式无效，请手动添加');return {items:out.items.filter(i=>ingredients[i.ingredientIdCandidate]).map(i=>({...i,qtyCandidate:Number.isFinite(i.qtyCandidate)&&i.qtyCandidate>0?i.qtyCandidate:1,unitCandidate:ingredients[i.ingredientIdCandidate].unit}))};}
 async parseDishPhoto(image){const out=await this.adapter.parseDishPhoto(image);if(!Array.isArray(out.dishNameCandidates)||typeof out.dishNameCandidates[0]!=='string')throw new Error('识别失败，请手动填写');return out;}
 async parseKitchenPhoto(image){const out=await this.adapter.parseKitchenPhoto(image);if(!Array.isArray(out.toolCandidates))throw new Error('识别失败，请手动添加厨具');return out;}
}
export const ai=new AIService();
