import {journalVisual} from './journal-visual.js';
import {recipes} from './data.js';
import {foodArt,escapeHtml as esc,glyph} from './assets.js';
// Editorial fixtures for the community preview; these are not live user posts.
export const communityPosts=[
 {id:'after-work',recipeId:'tomato_scrambled_egg',author:'小满的厨房',title:'下班后的第一口，还是家常味',caption:'忙了一天，最后还是想吃番茄炒蛋。留一点汤汁拌饭，简单的一餐也能吃得很满足。',tag:'家常一餐'},
 {id:'little-weekend',recipeId:'creamy_mushroom_pasta',author:'周末慢慢来',title:'给自己做一盘奶香蘑菇面',caption:'周末不赶时间，切好蘑菇，慢慢把这一餐做好。端上桌的时候，觉得一个人吃饭也很有仪式感。',tag:'一人食'},
 {id:'lunch-box',recipeId:'teriyaki_chicken_rice',author:'阿禾带饭记',title:'明天的午餐，今晚先期待',caption:'照烧鸡肉配米饭，是我的带饭灵感。酱汁不用太多，吃饭的时候再拌开就很满足。',tag:'带饭灵感'},
 {id:'warm-soup',recipeId:'miso_tofu_soup',author:'一碗热乎的',title:'给晚饭加一碗温柔的汤',caption:'香菇和豆腐放在一起，就很有家的感觉。今天不想吃得太复杂，一碗汤配一道家常菜刚刚好。',tag:'家常一餐'},
 {id:'fridge-rice',recipeId:'kimchi_fried_rice',author:'饭点见',title:'泡菜炒饭，唤醒今天的胃口',caption:'想换个口味的时候，就会想到泡菜炒饭。盛进喜欢的碗里，好好坐下来吃。',tag:'换换口味'},
 {id:'morning',recipeId:'cheese_omelette',author:'早起一小会',title:'留十分钟，认真吃个早饭',caption:'比起匆忙出门，更喜欢在家吃完再走。今天做芝士蛋饼，给早晨留一点暖乎乎的时间。',tag:'一人食'}
];

const postsFor=local=>[...local,...communityPosts];
const postImage=p=>p.local?journalVisual(p.record):foodArt(recipes.find(r=>r.id===p.recipeId));
export function communityCard(post,wanted){const r=recipes.find(r=>r.id===post.recipeId),saved=!!r&&wanted.some(w=>w.linkedRecipeId===r.id);return `<article class="journal-card community-card"><button class="community-open" data-action="community-open|${post.id}" aria-label="查看${esc(post.title)}">${postImage(post)}<div class="info"><small class="community-tag">${esc(post.tag)}${post.local?' · 本机分享':''}</small><h3>${esc(post.title)}</h3><p>${esc(post.caption)}</p></div></button><div class="community-byline"><span>${glyph('user')}${esc(post.author)}</span>${r?`<button class="community-save${saved?' selected':''}" data-action="want-recipe|${r.id}" aria-pressed="${saved}" aria-label="${saved?'取消想吃':'想吃'}${esc(r.name)}">${glyph(saved?'heart-fill':'heart')}</button>`:'<small>我的分享</small>'}</div></article>`;}
export function communityFeed(wanted,filter,local=[]){const rows=postsFor(local).filter(p=>filter==='全部'||p.tag===filter);return `<section class="community-feed"><div class="community-intro"><div><h2>看看大家的餐桌</h2><p>一道家常菜，也值得分享。</p></div></div><p class="community-preview-note">体验版：示例内容与本机分享，仅当前浏览器可见。</p><div class="community-filters" aria-label="分享分类">${['全部','家常一餐','一人食','带饭灵感','换换口味'].map(t=>`<button class="chip${filter===t?' active':''}" data-action="community-filter|${t}" aria-pressed="${filter===t}">${t}</button>`).join('')}</div><div class="journal-grid">${rows.map(p=>communityCard(p,wanted)).join('')}</div></section>`;}
export function communityDetail(id,wanted,local=[]){const p=postsFor(local).find(p=>p.id===id);if(!p)return '';const r=recipes.find(r=>r.id===p.recipeId),saved=!!r&&wanted.some(w=>w.linkedRecipeId===r.id);return `<div class="community-detail"><p class="note">${esc(p.author)} · ${p.local?'本机分享，仅当前浏览器可见':'示例分享'}</p>${postImage(p)}<h3>${esc(p.title)}</h3><p class="community-caption">${esc(p.caption)}</p>${r?`<div class="community-recipe"><strong>${esc(r.name)}</strong><small>${esc(r.cuisine)} · 约 ${r.totalTime} 分钟</small></div><button class="button${saved?' secondary':''}" data-action="want-recipe|${r.id}" aria-pressed="${saved}">${saved?'已加入想吃的 · 点击取消':'加入想吃的'}</button>`:''}${p.local?`<button class="text-button community-remove" data-action="community-remove|${p.id}">撤下这条本机分享</button>`:'<p class="note">加入后可在「想吃的」查看，也能在搭一篮时选入计划。</p>'}</div>`;}
export function communityComposer(draft,records){return `<div class="post-editor"><header class="post-editor-bar"><button data-action="close" class="post-cancel">取消</button><h2>发帖</h2><button data-action="community-publish" class="post-submit">发布</button></header><div class="post-editor-body"><div class="post-media${draft.record?' has-photo':''}">${draft.record?journalVisual(draft.record):''}<label class="post-photo-picker">${draft.record?'<span>更换照片</span>':glyph('plus-circle')+'<strong>晒晒今天的好吃的</strong><span>拍照或从相册选择</span>'}<input type="file" accept="image/*" data-field="community-photo" aria-label="选择发帖照片"></label></div>${!draft.record&&records.length?`<details class="post-records"><summary>也可以从吃过的选一餐</summary><div>${records.map(r=>`<button data-action="community-record|${r.id}">${journalVisual(r)}<span>${esc(r.title)}</span></button>`).join('')}</div></details>`:''}<input class="post-title" data-field="community-draft" data-id="title" maxlength="60" value="${esc(draft.title)}" placeholder="加个标题，让好吃的被发现" aria-label="帖子标题"><textarea class="post-caption" data-field="community-draft" data-id="caption" maxlength="300" placeholder="分享这一口的快乐，或你的小小做饭心得……" aria-label="帖子正文">${esc(draft.caption)}</textarea><div class="post-topics"><span>添加话题</span><div>${['家常一餐','一人食','带饭灵感','换换口味'].map(t=>`<button data-action="community-tag|${t}" class="${draft.tag===t?'active':''}" aria-pressed="${draft.tag===t}"># ${t}</button>`).join('')}</div></div><p class="post-visibility">本机体验 · 发布后仅当前浏览器可见</p></div></div>`;}
export function makeLocalPost(draft,author,id){if(!draft.record)throw new Error('请先选择照片或一条吃过的食记');if(!draft.title.trim())throw new Error('请给这一餐起个名字');return {id,local:true,title:draft.title.trim().slice(0,60),caption:draft.caption.trim().slice(0,300),tag:draft.tag,author:author||'我',record:structuredClone(draft.record),recipeId:draft.record.linkedRecipeId||(draft.record.recipeIds?.length===1?draft.record.recipeIds[0]:undefined),createdAt:new Date().toISOString()};}
