export const ingredients=Object.fromEntries([
 ['tomato','番茄','个','蔬菜','🍅'],['egg','鸡蛋','个','蛋奶','🥚'],['lettuce','生菜','把','蔬菜','🥬'],['spinach','菠菜','把','蔬菜','🌿'],['carrot','胡萝卜','根','蔬菜','🥕'],['onion','洋葱','个','蔬菜','🧅'],['potato','土豆','个','蔬菜','🥔'],['cucumber','黄瓜','根','蔬菜','🥒'],['mushroom','香菇','克','蔬菜','🍄'],['tofu','豆腐','克','豆制品','◻'],['chicken','鸡腿肉','克','肉类','🍗'],['pork','猪肉','克','肉类','🥩'],['broccoli','西兰花','克','蔬菜','🥦'],['corn','玉米','根','蔬菜','🌽'],['milk','牛奶','毫升','蛋奶','🥛'],['garlic','蒜','瓣','调味','🧄'],['scallion','小葱','根','调味','🌱'],['noodles','面条','克','主食','🍜'],['rice','大米','克','主食','🍚'],['cooking_oil','食用油','毫升','调味','🫙'],['soy','酱油','毫升','调味','🫙'],['salt','盐','克','调味','🧂']
].map(([id,name,unit,category,icon])=>[id,{id,name,unit,defaultUnit:unit,category,icon}]));
const recipe=(id,name,cuisine,type,time,tool,food,amounts,prep,heat,finish,allergens=[])=>({id,name,cuisine,subtype:type,totalTime:time,cookwareReq:[tool],servingBase:2,difficulty:'简单',flavorTags:['家常'],methodTags:[tool==='wok'?'炒':'煮'],food,ingredients:Object.entries(amounts).map(([ingredientId,qty])=>({ingredientId,qty,unit:ingredients[ingredientId].unit})),steps:{prep,heat,finish},allergens});
export const recipes=[
 recipe('tomato_scrambled_egg','番茄炒蛋','中式','米饭配菜',15,'wok','🍅',{tomato:2,egg:3,cooking_oil:10,salt:2},'番茄洗净切块，鸡蛋打散。','热锅下油，鸡蛋炒至凝固后盛出；番茄炒出汁，倒回鸡蛋炒匀。','加盐调味，确认鸡蛋完全凝固后盛盘。',['鸡蛋']),
 recipe('garlic_lettuce','蒜蓉生菜','中式','米饭配菜',10,'wok','🥬',{lettuce:1,garlic:2,cooking_oil:5,salt:1},'生菜掰开洗净沥干，蒜去皮切末。','热锅下油和蒜末，放入生菜翻炒至叶片变软。','加盐炒匀，最后出锅，趁热吃。'),
 recipe('miso_tofu_soup','香菇豆腐汤','日式','汤粥',18,'stockpot','🍲',{tofu:200,mushroom:100,scallion:1,salt:2},'豆腐切块，香菇洗净切片，小葱切末。','锅中加600毫升水，煮沸后加入香菇、豆腐，小火煮10分钟。','加盐和小葱，再煮1分钟。',['大豆']),
 recipe('teriyaki_chicken_rice','照烧鸡肉饭','日式','盖饭拌饭',30,'wok','🍗',{chicken:300,rice:150,soy:20,cooking_oil:5},'大米洗净；生鸡肉用独立砧板切块，处理后清洁双手与工具。','先煮米饭；炒锅下油煎鸡肉，加入酱油和50毫升水，加盖焖熟。','鸡肉中心达到74°C，收汁后配熟米饭。',['大豆']),
 recipe('creamy_mushroom_pasta','奶香蘑菇面','西式','面条米粉',25,'stockpot','🍝',{noodles:180,mushroom:150,milk:200,salt:2},'香菇洗净切片，准备牛奶和面条。','锅中加水煮沸，下面条按包装时间煮熟，沥去多余水；加入香菇和牛奶煮5分钟。','确认香菇煮熟，加盐调味。',['牛奶','小麦']),
 recipe('potato_egg','土豆炒鸡蛋','中式','米饭配菜',20,'wok','🥔',{potato:2,egg:2,cooking_oil:10,salt:2},'土豆去皮切薄片，鸡蛋打散。','热锅下油炒熟鸡蛋盛出；土豆加少量水焖软，放回鸡蛋翻炒。','土豆软熟、鸡蛋凝固后，加盐盛盘。',['鸡蛋'])
];
export const toolsCatalog=[['wok','炒锅','🍳'],['stockpot','汤锅','🍲'],['frying_pan','平底锅','🍳'],['steamer','蒸锅','♨'],['rice-cooker','电饭煲','🍚'],['air_fryer','空气炸锅','▣'],['microwave','微波炉','▤'],['oven','烤箱','▣'],['blender','料理机','▥'],['pressure_cooker','压力锅','♨']].map(([id,name,icon])=>({id,name,icon}));
export const styles=['中式','日式','韩式','西式','东南亚','还没想好'];
export const substyles={'中式':['家常','清蒸','香辣'],'日式':['盖饭','汤物'],'韩式':['拌饭','汤锅'],'西式':['意面','烤物'],'东南亚':['咖喱','酸辣'],'还没想好':[]};
export const newId=()=>globalThis.crypto.randomUUID();
export function initialState(){return {version:1,profile:{nickname:'Demo User',defaultDiners:2},diet:{allergies:[],absoluteAvoids:[]},kitchen:{stoveSlots:2,tools:toolsCatalog.filter(t=>['wok','stockpot','rice-cooker'].includes(t.id)).map(t=>({...t,quantity:1,available:true}))},cycle:{id:newId(),plannedDays:5,expectedMeals:3,styles:['中式','日式'],substyles:['家常'],anchorWantedDishIds:[],habits:[],carryOverEnabled:true},stock:[{id:newId(),ingredientId:'tomato',qty:3,unit:'个',acquiredAt:new Date().toISOString(),storage:'冷藏',status:'available'},{id:newId(),ingredientId:'egg',qty:6,unit:'个',acquiredAt:new Date().toISOString(),storage:'冷藏',status:'available'}],suggestions:[],purchases:[],wanted:recipes.map(r=>({id:'wanted-'+r.id,title:r.name,linkedRecipeId:r.id,nextBasketCandidate:false})),meal:{id:newId(),state:'browsing',diners:2,selectedRecipeIds:[],constraints:{mealType:'还没想好',timeLimit:60,operationPrefs:[],stockPolicy:'现有食材优先'},plan:null},records:[],completedSessionIds:[],purchaseCommits:[],notifications:false};}
