import {isPantry,pantryStatus,mealAdaptation,cookingNeeds,recipeView} from './food-rules.js';
import {scheduleMeal,validateScheduledPlan} from './scheduler.js';
import {ingredients,recipes,newId} from './data.js';
export function number(value,min=0,max=100000){const n=Number(value);if(!Number.isFinite(n)||n<min||n>max)throw new Error(`数量须在 ${min}–${max} 之间`);return n;}
export const totalStock=(state,id)=>state.stock.filter(l=>l.ingredientId===id&&l.status==='available').reduce((s,l)=>s+l.qty,0);
export function requirements(ids,diners=2){const result={};for(const id of ids){const r=recipes.find(r=>r.id===id);if(!r)throw new Error('菜谱不在已验证菜谱库中');for(const i of r.ingredients)result[i.ingredientId]=(result[i.ingredientId]||0)+i.qty*number(diners,1,12)/r.servingBase;}return Object.entries(result).map(([ingredientId,qty])=>({ingredientId,qty:Math.round(qty*100)/100,unit:ingredients[ingredientId].unit}));}
export function eligible(recipe,state){const avoids=[...state.diet.allergies,...state.diet.absoluteAvoids];return !avoids.some(a=>recipe.allergens.includes(a)||recipe.ingredients.some(i=>ingredients[i.ingredientId].name.includes(a)||({'鸡肉':'chicken','蘑菇':'mushroom','大豆':'tofu','奶':'milk','蛋':'egg'}[a]===i.ingredientId)))&&recipe.cookwareReq.every(id=>state.kitchen.tools.some(t=>t.id===id&&t.available&&t.quantity>0))&&state.kitchen.stoveSlots>0&&(recipe.id!=='teriyaki_chicken_rice'||state.kitchen.tools.some(t=>t.id==='rice-cooker'&&t.available&&t.quantity>0));}
export const shortages=(state,needs)=>needs.map(i=>({...i,missing:isPantry(i.ingredientId)?(pantryStatus(state,i.ingredientId)==='没有'?i.qty:0):Math.max(0,Math.round((i.qty-totalStock(state,i.ingredientId))*100)/100)})).filter(i=>i.missing>0);
export function commitPurchase(state,items,commitId){if(state.purchaseCommits.includes(commitId))return state;const selected=items.filter(i=>i.checked&&i.state!=='stock');if(!selected.length)throw new Error('请先勾选实际买到的食材');const next=structuredClone(state);for(const i of selected){if(!ingredients[i.ingredientId]||i.unit!==ingredients[i.ingredientId].unit)throw new Error('食材或单位不匹配');number(i.actualQty,0.01);if(isPantry(i.ingredientId)){next.pantry??={};next.pantry[i.ingredientId]='有';}next.stock.push({id:newId(),ingredientId:i.ingredientId,qty:Number(i.actualQty),unit:i.unit,acquiredAt:new Date().toISOString(),storage:'按包装储存',status:'available'});const p=next.purchases.find(p=>p.id===i.id);if(p){p.state='stock';p.actualQty=Number(i.actualQty);p.checked=false;}}next.purchaseCommits.push(commitId);return next;}
export function completeMeal(state,usage,saveRecord=true){if(state.completedSessionIds.includes(state.meal.id))return state;if(state.meal.state!=='cooking')throw new Error('请先开始做饭');if(cookingNeeds(state).some(i=>isPantry(i.ingredientId)&&pantryStatus(state,i.ingredientId)==='没有'))throw new Error('请确认常备调料是否备齐');const allowed=cookingNeeds(state).filter(i=>!isPantry(i.ingredientId)).map(i=>i.ingredientId);usage=usage.filter(i=>!isPantry(i.ingredientId));if(usage.length!==allowed.length||new Set(usage.map(i=>i.ingredientId)).size!==allowed.length||usage.some(i=>!allowed.includes(i.ingredientId)))throw new Error('实际用量与这餐食材不一致');for(const i of usage){number(i.qty);if(i.unit!==ingredients[i.ingredientId].unit)throw new Error('食材单位不匹配');if(i.qty>totalStock(state,i.ingredientId))throw new Error(`${ingredients[i.ingredientId].name}库存不足，请调整实际用量`);}const next=structuredClone(state);for(const i of usage){let remaining=Number(i.qty);const lots=next.stock.filter(l=>l.ingredientId===i.ingredientId&&l.status==='available').sort((a,b)=>a.acquiredAt.localeCompare(b.acquiredAt));for(const lot of lots){const used=Math.min(lot.qty,remaining);lot.qty=Math.round((lot.qty-used)*100)/100;remaining=Math.round((remaining-used)*100)/100;}}next.completedSessionIds.push(next.meal.id);next.meal.state='completed';if(saveRecord)next.records.unshift({id:newId(),sessionId:next.meal.id,recipeIds:[...next.meal.selectedRecipeIds],displayRecipeIds:state.meal.selectedRecipeIds.map(id=>recipeView(state,id).assetRecipeId||id),adaptedRecipes:state.meal.selectedRecipeIds.map(id=>recipeView(state,id)),title:state.meal.selectedRecipeIds.map(id=>recipeView(state,id).name).join(' · '),actualUsage:structuredClone(usage),eatenAt:new Date().toISOString(),note:''});return next;}
// Inventory state transitions above remain unchanged. Scheduling is a pure, validated calculation.
export function cookingPlan(state,strategy){if(!state.meal.selectedRecipeIds.length)throw new Error('先点心选一道菜');if(state.meal.selectedRecipeIds.some(id=>!recipes.some(r=>r.id===id&&eligible(r,state))))throw new Error('厨房或饮食限制已变化，请调整圆桌');if(shortages(state,cookingNeeds(state)).length)throw new Error('整餐库存不足，请补齐食材或减少菜品');return scheduleMeal(state,strategy);}
export function validateCookingPlan(plan,state){cookingPlan(state);return validateScheduledPlan(plan,state);}
