import {ingredients,recipes,newId} from './data.js';
export function number(value,min=0,max=100000){const n=Number(value);if(!Number.isFinite(n)||n<min||n>max)throw new Error(`数量须在 ${min}–${max} 之间`);return n;}
export const totalStock=(state,id)=>state.stock.filter(l=>l.ingredientId===id&&l.status==='available').reduce((s,l)=>s+l.qty,0);
export function requirements(ids,diners=2){const result={};for(const id of ids){const r=recipes.find(r=>r.id===id);if(!r)throw new Error('菜谱不在已验证菜谱库中');for(const i of r.ingredients)result[i.ingredientId]=(result[i.ingredientId]||0)+i.qty*number(diners,1,12)/r.servingBase;}return Object.entries(result).map(([ingredientId,qty])=>({ingredientId,qty:Math.round(qty*100)/100,unit:ingredients[ingredientId].unit}));}
export function eligible(recipe,state){const avoids=[...state.diet.allergies,...state.diet.absoluteAvoids];return !avoids.some(a=>recipe.allergens.includes(a)||recipe.ingredients.some(i=>ingredients[i.ingredientId].name.includes(a)||({'鸡肉':'chicken','蘑菇':'mushroom','大豆':'tofu','奶':'milk','蛋':'egg'}[a]===i.ingredientId)))&&recipe.cookwareReq.every(id=>state.kitchen.tools.some(t=>t.id===id&&t.available&&t.quantity>0))&&state.kitchen.stoveSlots>0&&(recipe.id!=='teriyaki_chicken_rice'||state.kitchen.tools.some(t=>t.id==='rice-cooker'&&t.available&&t.quantity>0));}
export const shortages=(state,needs)=>needs.map(i=>({...i,missing:Math.max(0,Math.round((i.qty-totalStock(state,i.ingredientId))*100)/100)})).filter(i=>i.missing>0);
export function commitPurchase(state,items,commitId){if(state.purchaseCommits.includes(commitId))return state;const selected=items.filter(i=>i.checked&&i.state!=='stock');if(!selected.length)throw new Error('请先勾选实际买到的食材');const next=structuredClone(state);for(const i of selected){if(!ingredients[i.ingredientId]||i.unit!==ingredients[i.ingredientId].unit)throw new Error('食材或单位不匹配');number(i.actualQty,0.01);next.stock.push({id:newId(),ingredientId:i.ingredientId,qty:Number(i.actualQty),unit:i.unit,acquiredAt:new Date().toISOString(),storage:'按包装储存',status:'available'});const p=next.purchases.find(p=>p.id===i.id);if(p){p.state='stock';p.actualQty=Number(i.actualQty);p.checked=false;}}next.purchaseCommits.push(commitId);return next;}
export function completeMeal(state,usage,saveRecord=true){if(state.completedSessionIds.includes(state.meal.id))return state;if(state.meal.state!=='cooking')throw new Error('请先开始做饭');const allowed=requirements(state.meal.selectedRecipeIds,state.meal.diners).map(i=>i.ingredientId);if(usage.length!==allowed.length||new Set(usage.map(i=>i.ingredientId)).size!==allowed.length||usage.some(i=>!allowed.includes(i.ingredientId)))throw new Error('实际用量与这餐食材不一致');for(const i of usage){number(i.qty);if(i.unit!==ingredients[i.ingredientId].unit)throw new Error('食材单位不匹配');if(i.qty>totalStock(state,i.ingredientId))throw new Error(`${ingredients[i.ingredientId].name}库存不足，请调整实际用量`);}const next=structuredClone(state);for(const i of usage){let remaining=Number(i.qty);const lots=next.stock.filter(l=>l.ingredientId===i.ingredientId&&l.status==='available').sort((a,b)=>a.acquiredAt.localeCompare(b.acquiredAt));for(const lot of lots){const used=Math.min(lot.qty,remaining);lot.qty=Math.round((lot.qty-used)*100)/100;remaining=Math.round((remaining-used)*100)/100;}}next.completedSessionIds.push(next.meal.id);next.meal.state='completed';if(saveRecord)next.records.unshift({id:newId(),sessionId:next.meal.id,recipeIds:[...next.meal.selectedRecipeIds],title:next.meal.selectedRecipeIds.map(id=>recipes.find(r=>r.id===id).name).join(' · '),actualUsage:structuredClone(usage),eatenAt:new Date().toISOString(),note:''});return next;}
// Deterministic scheduling: one shared preparation stage, resource-constrained heat tasks,
// rice waiting can overlap, and quick greens are deliberately served last.
export function cookingPlan(state){const selected=state.meal.selectedRecipeIds.map(id=>recipes.find(r=>r.id===id));if(!selected.length)throw new Error('先点心选一道菜');if(selected.some(r=>!eligible(r,state)))throw new Error('厨房或饮食限制已变化，请调整圆桌');const missing=shortages(state,requirements(state.meal.selectedRecipeIds,state.meal.diners));if(missing.length)throw new Error('整餐库存不足，请补齐食材或减少菜品');const stages=[{id:'prep',title:'一起洗切，分开处理',start:0,end:6,resource:'操作台',text:selected.map(r=>r.steps.prep).join(' '),kind:'prep'}];const stove=Array.from({length:state.kitchen.stoveSlots},()=>6);const toolEnds={};let riceEnd=6;if(selected.some(r=>r.id==='teriyaki_chicken_rice')){riceEnd=31;stages.push({id:'rice',title:'米饭先煮上',start:6,end:31,resource:'电饭煲',text:'按电饭煲刻度加水，启动煮饭。等待时进行下面的炒菜与汤。',kind:'wait'});}for(const r of [...selected].sort((a,b)=>(a.id==='garlic_lettuce')-(b.id==='garlic_lettuce')||b.totalTime-a.totalTime)){const tool=r.cookwareReq[0];const count=state.kitchen.tools.find(t=>t.id===tool).quantity;toolEnds[tool]??=Array(count).fill(6);let slot=stove.indexOf(Math.min(...stove)),pot=toolEnds[tool].indexOf(Math.min(...toolEnds[tool]));let start=Math.max(stove[slot],toolEnds[tool][pot]);if(r.id==='garlic_lettuce')start=Math.max(start,...stages.map(s=>s.end))-3;start=Math.max(6,start,stove[slot],toolEnds[tool][pot]);const end=start+Math.max(5,r.totalTime-6);stove[slot]=end;toolEnds[tool][pot]=end;stages.push({id:r.id,title:r.name,start,end,resource:`灶位 ${slot+1} · ${state.kitchen.tools.find(t=>t.id===tool).name}`,text:r.steps.heat+' '+r.steps.finish,kind:'heat'});}const end=Math.max(riceEnd,...stages.map(s=>s.end));stages.sort((a,b)=>a.start-b.start);stages.push({id:'finish',title:'一起上桌',start:end,end,resource:'餐桌',text:'确认所有食材熟透，关火。完成后核对这一餐的实际用量。',kind:'finish'});return {estimatedTotalMinutes:end,strategyTags:['合并洗切',state.kitchen.stoveSlots>1?'按灶位协同':'单灶顺序出菜','快手蔬菜靠后'],stages};}
export function validateCookingPlan(plan,state){
 const baseline=cookingPlan(state);
 if(!plan||!Array.isArray(plan.stages)||!Array.isArray(plan.strategyTags))throw new Error('教程格式无效');
 const expected=new Set(baseline.stages.map(s=>s.id));
 if(plan.stages.length!==expected.size||new Set(plan.stages.map(s=>s.id)).size!==expected.size)throw new Error('教程步骤不完整');
 for(const s of plan.stages){if(!expected.has(s.id)||typeof s.title!=='string'||typeof s.text!=='string'||typeof s.resource!=='string'||!Number.isFinite(s.start)||!Number.isFinite(s.end)||s.start<0||s.end<s.start)throw new Error('教程步骤校验失败');const source=baseline.stages.find(x=>x.id===s.id);if(s.kind!==source.kind||s.end-s.start<source.end-source.start)throw new Error('教程缺少必要步骤或时长');}
 const prep=plan.stages.find(s=>s.id==='prep');if(prep.start!==0)throw new Error('先完成准备再烹饪');
 const heats=plan.stages.filter(s=>s.kind==='heat');
 for(const s of heats){const match=s.resource.match(/^灶位 (\d+) · (.+)$/);if(!match||Number(match[1])>state.kitchen.stoveSlots||Number(match[1])<1||s.start<prep.end)throw new Error('教程灶位或依赖冲突');const tool=state.kitchen.tools.find(t=>t.id===recipes.find(r=>r.id===s.id).cookwareReq[0]);if(match[2]!==tool.name)throw new Error('教程锅具不匹配');}
 for(const s of heats){const concurrent=heats.filter(x=>x.start<=s.start&&x.end>s.start);if(new Set(concurrent.map(x=>x.resource.split(' · ')[0])).size!==concurrent.length)throw new Error('灶位时间冲突');for(const t of state.kitchen.tools){if(concurrent.filter(x=>recipes.find(r=>r.id===x.id).cookwareReq.includes(t.id)).length>t.quantity)throw new Error('锅具时间冲突');}}
 const finish=plan.stages.find(s=>s.id==='finish'),end=Math.max(...plan.stages.filter(s=>s.id!=='finish').map(s=>s.end));if(finish.start<end||plan.estimatedTotalMinutes<finish.end||!Number.isFinite(plan.estimatedTotalMinutes))throw new Error('出锅顺序或总时长无效');
 // Keep verified recipe instructions; let the adapter propose timing and sequencing only.
 return {...plan,stages:plan.stages.map(s=>({...s,text:baseline.stages.find(x=>x.id===s.id).text})).sort((a,b)=>a.start-b.start),strategyTags:plan.strategyTags.filter(t=>typeof t==='string')};
}
