import {isPantry,pantryStatus,plannerQty,mealAdaptation,cycleGoals,candidateAssessment,recipeView,adaptationCodes} from './food-rules.js';
import {scheduleMeal} from './scheduler.js';
import {recipes,ingredients} from './data.js';
import {eligible,requirements,shortages,totalStock} from './domain.js';
import {reasonText} from './ai-context.js';
export const anchors=s=>[...new Set(s.cycle.anchorWantedDishIds.map(id=>s.wanted.find(w=>w.id===id)?.linkedRecipeId).filter(Boolean))];
const recent=s=>s.records.slice(0,5).flatMap(r=>r.recipeIds||[]);
const ids=r=>r.ingredients.map(i=>i.ingredientId);
export function verifiedReasons(r,s){const selected=[...new Set([...s.meal.selectedRecipeIds,r.id])];let duration=Infinity;try{if(selected.every(id=>eligible(recipes.find(r=>r.id===id),s)))duration=scheduleMeal({...s,meal:{...s.meal,selectedRecipeIds:selected}}).optimizedMinutes;}catch{/* Existing table may no longer fit the kitchen; candidates remain usable. */}const adaptation=candidateAssessment(s,r.id),needs=adaptation.requirements,table=recipes.filter(x=>s.meal.selectedRecipeIds.includes(x.id));return [
 adaptation.canCookNow&&'stock_ready',adaptation.adaptations.length>0&&'adaptable',needs.some(i=>totalStock(s,i.ingredientId)>0)&&'uses_existing_stock',duration<=Math.min(s.meal.constraints.timeLimit,s.meal.constraints.operationPrefs.includes('20分钟内')?20:Infinity)&&'fits_time',(s.meal.constraints.cuisines||[]).includes(r.cuisine)&&'matches_cuisine',(s.meal.constraints.flavors||[]).some(f=>r.flavorTags.includes(f))&&'matches_flavor',s.meal.constraints.mealType===r.mealType&&'matches_meal_type',r.prepEffort===1&&'low_prep',r.cleanupScore===1&&'low_cleanup',table.some(t=>t.id!==r.id&&ids(t).some(id=>ids(r).includes(id)&&ingredients[id].category!=='调味'))&&'complements_table',!recent(s).includes(r.id)&&'avoids_recent_repeat',anchors(s).includes(r.id)&&'anchor_related'].filter(Boolean);}
export function verifiedInsights(refs,s){const unique=recipes.filter(r=>refs.includes(r.id));const out=[];for(const id of [...new Set(unique.flatMap(ids))].filter(id=>ingredients[id].category!=='调味')){const uses=unique.filter(r=>ids(r).includes(id)).map(r=>r.id);if(plannerQty(s,id)>0)out.push({type:'reuse_existing',ingredientId:id,recipeIds:uses,messageCode:'reuse_existing'});if(uses.length>1)out.push({type:'shared_ingredient',ingredientId:id,recipeIds:uses,messageCode:'shared_ingredient'});if(uses.length===1&&!plannerQty(s,id)&&ingredients[id].category!=='调味')out.push({type:'one_off_purchase',ingredientId:id,recipeIds:uses,messageCode:'one_off_purchase'});}return out;}
export function insightText(i){const name=ingredients[i.ingredientId]?.name||'';return {reuse_existing:`优先用已有的${name}`,shared_ingredient:`${name}能在几顿里接着用，少买几样也能换着做`,one_off_purchase:`${name}只用到一次，按需少买一点`}[i.messageCode]||'';}
export function basketPlanningIssue(s){
 if(!s.kitchen.tools.some(t=>t.available&&t.quantity>0))return '还没选择家里的厨具，请先勾选你实际有的锅具。';
 if(!(s.kitchen.stoveSlots>0))return '请在「我的厨房」确认可用灶位。';
 const kitchenOnly={...s,diet:{allergies:[],absoluteAvoids:[]}};
 if(!recipes.some(r=>eligible(r,kitchenOnly)))return '当前菜库还没有适合这些厨具的做法，请核对家里是否还有炒锅或汤锅。';
 if(!recipes.some(r=>eligible(r,s)))return '当前菜库还没有符合你饮食限制的菜谱，请核对过敏与忌口设置；真实限制请保留。';
 return '';
}
export function basicPlan(s){const valid=recipes.filter(r=>eligible(r,s));if(!valid.length)throw new Error(basketPlanningIssue(s));const picked=anchors(s);if(picked.some(id=>!valid.some(r=>r.id===id)))throw new Error('锚点菜与饮食或厨具限制冲突');const goals=s.cycle.goals||[],objective=goals.includes('换换口味')?'variety':'balanced',count=Math.max(s.cycle.expectedMeals*2,picked.length);while(picked.length<count){const chosen=recipes.filter(r=>picked.includes(r.id));const known=new Set(chosen.flatMap(ids));const score=r=>{const use=ids(r).filter(id=>plannerQty(s,id)>0).length;const sharing=ids(r).filter(id=>known.has(id)).length;const newItems=ids(r).filter(id=>!known.has(id)&&!plannerQty(s,id)&&ingredients[id].category!=='调味').length;return use*4+sharing*2-newItems+goalScore(r,goals)+(goals.includes('肉蛋奶都来点')?r.ingredients.filter(i=>['蛋奶','豆制品','肉类'].includes(ingredients[i.ingredientId].category)&&!chosen.some(c=>c.ingredients.some(j=>ingredients[j.ingredientId].category===ingredients[i.ingredientId].category))).length*18:0)-(recent(s).includes(r.id)?objective==='variety'?16:5:0)-(picked.filter(id=>id===r.id).length*(objective==='variety'?30:12))+(objective==='variety'&&!chosen.some(c=>c.cuisine===r.cuisine)?12:0)+(objective==='variety'&&!chosen.some(c=>c.methodTags[0]===r.methodTags[0])?6:0)-(objective==='easy'?r.prepEffort*4:0)-(objective==='easy'?r.cleanupScore*3:0);};picked.push([...valid].sort((a,b)=>score(b)-score(a)||a.id.localeCompare(b.id))[0].id);}
 return {referenceRecipeIds:picked,planningStrategy:['preserve_anchor','reuse_stock','reuse_ingredients',objective==='easy'?'reduce_prep_effort':objective==='variety'?'increase_variety':'reduce_one_off_purchase'],planningInsights:verifiedInsights(picked,s).slice(0,8),tradeoffs:[],meta:{source:'mock'}};}
export function basicRecommendations(s){const prefs=s.meal.constraints.operationPrefs;const cards=recipes.filter(r=>candidateAssessment(s,r.id).allowed).map(r=>{const codes=verifiedReasons(r,s);const missing=candidateAssessment(s,r.id).missing;const weights={stock_ready:45,uses_existing_stock:6,fits_time:8,matches_cuisine:30,matches_flavor:30,adaptable:4,matches_meal_type:10,low_prep:prefs.includes('少切配')?18:2,low_cleanup:prefs.includes('少洗锅')?18:2,complements_table:12,avoids_recent_repeat:12,anchor_related:7};return {recipeId:r.id,reasonCodes:codes,score:(codes.includes('fits_time')?0:-30)+codes.reduce((n,c)=>n+(weights[c]||0),0)+goalScore(r,s.cycle.goals||[])-missing.length*(s.meal.constraints.stockPolicy==='现有食材优先'?8:2)-(prefs.includes('一锅出')&&r.cookwareReq.length>1?25:0)};});return {recipeCards:cards.sort((a,b)=>b.score-a.score||a.recipeId.localeCompare(b.recipeId)),meta:{source:'mock'}};}
export function shortReason(codes){return codes.slice(0,2).map(c=>reasonText[c]).filter(Boolean).join(' · ');}
function goalScore(r,goals){const cats=r.ingredients.map(i=>ingredients[i.ingredientId].category);return (goals.includes('蔬菜多一点')?cats.filter(c=>c==='蔬菜').length*6:0)+(goals.includes('肉蛋奶都来点')&&cats.some(c=>['蛋奶','豆制品','肉类'].includes(c))?10:0)+(goals.includes('适合带饭')?(r.mealPrepSuitability?12:-16):0)+(goals.includes('耐放一点')?r.ingredients.filter(i=>['potato','carrot','onion','rice','noodles'].includes(i.ingredientId)).length*8:0);}
export function planningMessages(refs,s){const dishes=recipes.filter(r=>refs.includes(r.id)),messages=[],used=[...new Set(dishes.flatMap(ids))].filter(id=>!isPantry(id)&&plannerQty(s,id)>0);if(used.length)messages.push(`家里的${used.slice(0,3).map(id=>ingredients[id].name).join('、')}已经算进去了`);for(const goal of s.cycle.goals||[]){if(goal==='蔬菜多一点'){const count=dishes.filter(r=>r.ingredients.some(i=>ingredients[i.ingredientId].category==='蔬菜')).length;if(count)messages.push(`按你想多些蔬菜的偏好，这次搭了 ${count} 道带蔬菜的菜`);}if(goal==='偏素一点'&&dishes.some(r=>!r.ingredients.some(i=>ingredients[i.ingredientId].category==='肉类')))messages.push('这次搭了几样不用肉也能做的菜');if(goal==='省心快手'&&dishes.some(r=>r.handsOnTime<=12))messages.push('搭了几样动手步骤少的菜，忙的时候也方便做');if(goal==='适合带饭'&&dishes.every(r=>r.mealPrepSuitability))messages.push('这次选的菜都适合装成便当，做好后仍需妥善冷藏和充分复热');}const shared=verifiedInsights(refs,s).find(i=>i.type==='shared_ingredient');if(shared)messages.push(insightText(shared));if(recent(s).length&&dishes.every(r=>!recent(s).includes(r.id)))messages.push('避开了最近吃过的菜，换几样口味');return [...new Set(messages)].slice(0,3);}
// Keep the explicitly chosen cuisine. Relax only other preferences within that cuisine.
export function applyDirection(cards,s){const c=s.meal.constraints,selected=s.meal.selectedRecipeIds;const cuisineCards=c.cuisines?.length?cards.filter(card=>c.cuisines.includes(recipes.find(r=>r.id===card.recipeId).cuisine)):cards;if(c.cuisines?.length&&!cuisineCards.length)return {recipeCards:[],relaxations:['菜系'],directionMessage:`按当前库存、人数和已选菜，暂时没有可加入的${c.cuisines.join('、')}菜。可以调整食材策略，或按库存看其他搭配。`};const entries=cuisineCards.map(card=>{const r=recipes.find(r=>r.id===card.recipeId),reasons=verifiedReasons(r,s),miss=[];if(c.cuisines?.length&&!c.cuisines.includes(r.cuisine))miss.push('菜系');if(c.flavors?.length&&!c.flavors.some(f=>r.flavorTags.includes(f)))miss.push('口味');if(c.mealType!=='还没想好'&&r.mealType!==c.mealType)miss.push('餐食形式');if((c.timeLimit<180||c.operationPrefs.includes('20分钟内'))&&!reasons.includes('fits_time'))miss.push('时间');if(c.operationPrefs.includes('少洗锅')&&(r.cleanupScore>1||selected.length&&r.cookwareReq.some(tool=>!selected.some(id=>recipes.find(x=>x.id===id).cookwareReq.includes(tool)))))miss.push('少洗锅');if(c.operationPrefs.includes('少切配')&&r.prepEffort>1)miss.push('少切配');if(c.operationPrefs.includes('一锅出')&&new Set([...selected,r.id].flatMap(id=>recipes.find(x=>x.id===id).cookwareReq)).size>1)miss.push('一锅出');return {card,miss};});const minimum=Math.min(...entries.map(e=>e.miss.length));const matched=entries.filter(e=>e.miss.length===minimum);const relaxations=matched.length&&minimum?matched[0].miss:[];const filtered=minimum?matched.filter(e=>JSON.stringify(e.miss)===JSON.stringify(relaxations)):matched;return {recipeCards:filtered.map(e=>e.card),relaxations,directionMessage:relaxations.length?`暂时没有完全符合的菜，先放宽${relaxations.join('、')}，看看这些。`:''};}

// Recheck model/local candidates against the complete table before a card can be displayed.
export function resolveRecipeCards(cards,s){const seen=new Set(),resolved=[];for(const card of cards){const source=recipes.find(r=>r.id===card.recipeId);if(!source)continue;const first=candidateAssessment(s,source.id);if(!first.allowed)continue;const view=first.adaptedRecipes.find(r=>r.baseRecipeId===source.id),id=source.id;if(seen.has(view.name))continue;const adaptation=first;seen.add(view.name);const r=recipes.find(r=>r.id===id),reasonCodes=verifiedReasons(r,s);const own=adaptation.adaptations.filter(a=>a.recipeId===id);resolved.push({...card,recipeId:id,adaptedRecipe:view,displayName:view.name,reasonCodes,adaptationCodes:adaptationCodes(adaptation.adaptations),cookability:adaptation.cookability,canCookNow:adaptation.canCookNow,missingIngredients:adaptation.missing,adaptations:adaptation.adaptations,purchaseSuggestions:adaptation.purchaseSuggestions,shortReason:adaptation.missing.length?`补 ${adaptation.missing.length} 样可做`:own.length?own[0].message:'现有食材可做'});}return applyDirection(resolved.sort((a,b)=>Number(a.cookability==='needs_purchase')-Number(b.cookability==='needs_purchase')),s);}

// Vary the first few equally cookable matches without admitting less suitable recipes.
export function rotateRecipeCards(cards,previousFirst,random=Math.random){const result=[...cards];if(result.length<2)return result;const ready=result[0].canCookNow;let end=1;while(end<Math.min(4,result.length)&&result[end].canCookNow===ready)end++;if(end<2)return result;const alternatives=result.slice(0,end).map((card,index)=>({card,index})).filter(x=>x.card.recipeId!==previousFirst);const chosen=alternatives[Math.floor(random()*alternatives.length)];if(chosen){const [card]=result.splice(chosen.index,1);result.unshift(card);}return result;}
