import {adaptedRecipe,mealAdaptation} from './food-rules.js';
import {recipes} from './data.js';
const overlap=(a,b)=>a.start<b.end&&b.start<a.end;
const fail=m=>{throw new Error(m);};
export function validateStrategy(out,state){
 const selected=state.meal.selectedRecipeIds;
 if(!out||typeof out!=='object'||Object.keys(out).some(k=>!['preferredOrder','sharedPrep','parallelCandidates','reuseCookware','priority','waitingTimeUse','toolAssignments'].includes(k)))fail('烹饪策略格式无效');
 if(!Array.isArray(out.preferredOrder)||out.preferredOrder.length!==selected.length||new Set(out.preferredOrder).size!==selected.length||out.preferredOrder.some(id=>!selected.includes(id)))fail('策略菜品不匹配');
 const nodes=new Set(selected.flatMap(id=>adaptedRecipe(recipes.find(r=>r.id===id),state).atomicSteps.map(s=>id+'/'+s.id)));
 for(const key of ['sharedPrep','parallelCandidates','waitingTimeUse'])if(!Array.isArray(out[key])||out[key].length>20||out[key].some(pair=>!Array.isArray(pair)||pair.length!==2||pair.some(id=>!nodes.has(id))||pair[0]===pair[1]))fail('策略步骤不存在');
 if(!Array.isArray(out.reuseCookware)||out.reuseCookware.some(id=>!state.kitchen.tools.some(t=>t.id===id&&t.available)))fail('策略锅具不可用');
 if(!['balanced','less_cleanup','less_prep','fast'].includes(out.priority))fail('策略优先级无效');
 if(out.toolAssignments&&!Array.isArray(out.toolAssignments))fail('锅具分配格式无效');for(const assignment of out.toolAssignments||[]){if(!assignment||Object.keys(assignment).some(k=>!['recipeId','toolId'].includes(k)))fail('锅具分配格式无效');const r=recipes.find(r=>r.id===assignment.recipeId);if(!selected.includes(assignment.recipeId)||!r||!(r.cookwareAlternatives||[r.cookwareReq[0]]).includes(assignment.toolId)||!state.kitchen.tools.some(t=>t.id===assignment.toolId&&t.available&&t.quantity>0))fail('锅具分配无效');}if(out.toolAssignments&&!Array.isArray(out.toolAssignments))fail('锅具分配格式无效');if(new Set((out.toolAssignments||[]).map(x=>x.recipeId)).size!==(out.toolAssignments||[]).length)fail('锅具分配重复');
 return out;
}
export function basicStrategy(state){const selected=state.meal.selectedRecipeIds;const prefs=state.meal.constraints.operationPrefs;const ordered=[...selected].sort((a,b)=>Number(a==='garlic_lettuce')-Number(b==='garlic_lettuce')||recipes.find(r=>r.id===b).totalTime-recipes.find(r=>r.id===a).totalTime);const separate=selected.includes('tomato_pasta')&&selected.some(id=>id!=='tomato_pasta'&&recipes.find(r=>r.id===id).cookwareReq[0]==='stockpot')&&state.kitchen.tools.some(t=>t.id==='wok'&&t.available&&t.quantity>0)&&!prefs.includes('一锅出')&&!prefs.includes('少洗锅');return {toolAssignments:separate?[{recipeId:'tomato_pasta',toolId:'wok'}]:[],preferredOrder:ordered,sharedPrep:[],parallelCandidates:[],reuseCookware:[...new Set(selected.flatMap(id=>recipes.find(r=>r.id===id).cookwareReq))],priority:prefs.includes('少洗锅')?'less_cleanup':prefs.includes('少切配')?'less_prep':'fast',waitingTimeUse:[]};}
function schedule(state,selected,strategy,merge=true){
 const units=[],aliases=new Map(),wash=new Map(),factor=Math.max(1,state.meal.diners/2);
 for(const r of selected){const mapped=r.atomicSteps.map(s=>({...s,id:r.id+'/'+s.id,recipeId:r.id,recipeIds:[r.id],duration:Math.ceil(s.duration*(s.handsOn?factor:1)),dependencies:s.dependencies.map(id=>r.id+'/'+id)}));
  for(const s of mapped.filter(s=>s.phase==='wash')){const key=s.ingredientIds[0];if(merge&&wash.has(key)){const old=wash.get(key);old.recipeIds.push(r.id);aliases.set(s.id,old.id);}else{wash.set(key,s);units.push({id:s.id,steps:[s],tool:null});}}
  for(const [phase,filter,tool] of [['prep',s=>s.phase==='prep',null],['rice',s=>s.phase.startsWith('appliance'),'rice-cooker'],['heat',s=>s.phase==='heat'||s.phase==='finish',strategy.toolAssignments?.find(a=>a.recipeId===r.id)?.toolId||r.cookwareReq[0]]]){const steps=mapped.filter(filter);if(steps.length)units.push({id:r.id+'/'+phase,steps,tool});}
 }
 const alias=id=>aliases.get(id)||id;
 for(const u of units){let offset=0;for(const s of u.steps){s.dependencies=s.dependencies.map(alias);s.offset=offset;offset+=s.duration;}u.duration=offset;const internal=new Set(u.steps.map(s=>s.id));u.external=u.steps.flatMap(s=>s.dependencies.filter(d=>!internal.has(d)).map(id=>({id,offset:s.offset})));}
 const reservations=new Map(),ends=new Map(),timeline=[],remaining=[...units];
 const free=(resource,start,end)=>(reservations.get(resource)||[]).every(r=>!overlap(r,{start,end}));
 const reserve=(resource,start,end)=>{if(!reservations.has(resource))reservations.set(resource,[]);reservations.get(resource).push({start,end});};
 while(remaining.length){const ready=remaining.filter(u=>u.external.every(d=>ends.has(d.id)));if(!ready.length)fail('步骤依赖有环或缺失');
  const candidates=ready.map(u=>{const earliest=Math.max(0,...u.external.map(d=>ends.get(d.id)-d.offset));const tool=state.kitchen.tools.find(t=>t.id===u.tool&&t.available);if(u.tool&&!tool)fail('缺少可用厨具');const lanes=u.tool?Array.from({length:tool.quantity},(_,i)=>u.tool+'#'+(i+1)):[''];const stove=u.tool&&u.tool!=='rice-cooker'&&u.tool!=='mixing_bowl'?Array.from({length:state.kitchen.stoveSlots},(_,i)=>'stove#'+(i+1)):[''];let best;
   for(const lane of lanes)for(const slot of stove){let start=earliest;for(;start<10000;start++){if([lane,slot].filter(Boolean).some(x=>!free(x,start,start+u.duration)))continue;if(u.steps.some(s=>s.handsOn&&!free('hands',start+s.offset,start+s.offset+s.duration)))continue;break;}if(start>=10000)fail('无法安排资源');const cost=start+(strategy.priority==='less_cleanup'&&lane&&!reservations.has(lane)?10000:0);if(!best||cost<best.cost)best={u,start,lane,slot,cost};}return best;});
  candidates.sort((a,b)=>a.cost-b.cost||strategy.preferredOrder.indexOf(a.u.steps[0].recipeId)-strategy.preferredOrder.indexOf(b.u.steps[0].recipeId)||a.u.id.localeCompare(b.u.id));const {u,start,lane,slot}=candidates[0];
  for(const resource of [lane,slot].filter(Boolean))reserve(resource,start,start+u.duration);
  for(const s of u.steps){const begin=start+s.offset,end=begin+s.duration;if(s.handsOn)reserve('hands',begin,end);ends.set(s.id,end);timeline.push({...s,start:begin,end,toolLane:lane,stoveLane:slot,resource:slot?`灶位 ${slot.split('#')[1]} · ${state.kitchen.tools.find(t=>t.id===u.tool).name}`:lane?state.kitchen.tools.find(t=>t.id===u.tool).name:'操作台',kind:['wash','prep'].includes(s.phase)?'prep':s.phase==='finish'?'finish':s.handsOn?'heat':'wait',text:s.instruction,title:s.instruction.split(/[，。；]/)[0]});}
  remaining.splice(remaining.indexOf(u),1);
 }
 const end=Math.max(...timeline.map(s=>s.end));return {timeline:timeline.sort((a,b)=>a.start-b.start||a.id.localeCompare(b.id)),end,reservations};
}
export function scheduleMeal(state,proposal){
 const adaptedMeal=mealAdaptation(state),selected=adaptedMeal.adaptedRecipes;if(!selected.length||selected.some(r=>!r))fail('先选择有效菜品');
 let strategy,corrected=false;const {meta,...candidate}=proposal||basicStrategy(state);try{strategy=validateStrategy(candidate,state);}catch{strategy=basicStrategy(state);corrected=true;}
 const userPrefs=state.meal.constraints.operationPrefs;if(userPrefs.includes('少洗锅')||userPrefs.includes('一锅出'))strategy={...strategy,priority:'less_cleanup'};else if(userPrefs.includes('少切配'))strategy={...strategy,priority:'less_prep'};else strategy={...strategy,priority:'fast'};if(userPrefs.includes('20分钟内'))state={...state,meal:{...state.meal,constraints:{...state.meal.constraints,timeLimit:Math.min(20,state.meal.constraints.timeLimit)}}};
 const standard=!userPrefs.length&&state.meal.constraints.timeLimit>=60;strategy={...strategy,toolAssignments:strategy.toolAssignments||basicStrategy(state).toolAssignments};let result=schedule(state,selected,strategy);const baseline=selected.reduce((n,r)=>n+schedule(state,[r],{...basicStrategy(state),preferredOrder:[r.id]},false).end,0);
 // Compare safe deterministic alternatives; an LLM ordering cannot make the displayed optimization worse.
 const prefs=state.meal.constraints.operationPrefs;const fast={...basicStrategy(state),priority:'fast'};const alternative=schedule(state,selected,fast);
 const cleanupPreferred=prefs.includes('少洗锅')||prefs.includes('一锅出');if(result.end>baseline||(!cleanupPreferred&&alternative.end<result.end)||(state.meal.constraints.timeLimit<result.end&&alternative.end<result.end)){result=alternative;corrected=true;}
 const boundaries=[...new Set(result.timeline.flatMap(s=>[s.start,s.end]))].sort((a,b)=>a-b),parallelWindows=[];
 for(let i=0;i<boundaries.length-1;i++){const start=boundaries[i],end=boundaries[i+1],steps=result.timeline.filter(s=>s.start<=start&&s.end>=end);if(new Set(steps.map(s=>s.recipeId)).size>1)parallelWindows.push({start,end,stepIds:steps.map(s=>s.id)});}
 for(const pair of [...strategy.parallelCandidates,...strategy.waitingTimeUse]){const a=result.timeline.find(s=>s.id===pair[0]),b=result.timeline.find(s=>s.id===pair[1]);if(!a||!b||!overlap(a,b))corrected=true;}for(const pair of strategy.sharedPrep){if(!result.timeline.some(s=>s.recipeIds.includes(pair[0].split('/')[0])&&s.recipeIds.includes(pair[1].split('/')[0])&&s.recipeIds.length>1))corrected=true;}
 const optimizedMinutes=result.end,tradeoffs=[];if(optimizedMinutes>state.meal.constraints.timeLimit)tradeoffs.push(`实际排程约 ${optimizedMinutes} 分钟，超过这顿 ${state.meal.constraints.timeLimit} 分钟的偏好。`);
 const usedCookware=[...result.reservations.keys()].filter(k=>!k.startsWith('stove')&&k!=='hands');
 if(prefs.includes('一锅出')&&usedCookware.length>1)tradeoffs.push('所选菜品需要多件锅具，无法满足一锅出。');
 return {version:2,adaptedRecipes:selected,requirements:adaptedMeal.requirements,adaptations:adaptedMeal.adaptations,cookingMode:standard?'standard':strategy.priority,estimatedTotalMinutes:optimizedMinutes,sequentialMinutes:baseline,optimizedMinutes,savedMinutes:baseline-optimizedMinutes,parallelWindows,atomicTimeline:result.timeline,stages:result.timeline,strategyTags:['按依赖与资源编排',parallelWindows.length?'等待时穿插操作':'顺序操作'],strategyCorrected:corrected,tradeoffs,usedCookware,sharedPrep:result.timeline.filter(s=>s.recipeIds.length>1).map(s=>({stepId:s.id,recipeIds:s.recipeIds,ingredientIds:s.ingredientIds}))};
}
export function validateScheduledPlan(plan,state){
 const canonical=scheduleMeal(state);if(!plan||!Array.isArray(plan.atomicTimeline))fail('教程格式无效');
 if(JSON.stringify(plan.adaptedRecipes)!==JSON.stringify(canonical.adaptedRecipes)||JSON.stringify(plan.requirements)!==JSON.stringify(canonical.requirements))fail('适配菜谱不可修改');
 const expected=new Map(canonical.atomicTimeline.map(s=>[s.id,s]));if(plan.atomicTimeline.length!==expected.size||new Set(plan.atomicTimeline.map(s=>s.id)).size!==expected.size)fail('教程步骤不完整');
 const byId=new Map(plan.atomicTimeline.map(s=>[s.id,s]));
 for(const s of plan.atomicTimeline){const base=expected.get(s.id);if(!base||!Number.isFinite(s.start)||!Number.isFinite(s.end)||s.start<0||s.end-s.start!==base.duration||s.action!==base.action||s.text!==base.text||s.handsOn!==base.handsOn||s.phase!==base.phase||s.recipeId!==base.recipeId||JSON.stringify(s.recipeIds)!==JSON.stringify(base.recipeIds)||JSON.stringify(s.ingredientIds)!==JSON.stringify(base.ingredientIds)||s.instruction!==base.instruction||JSON.stringify(s.dependencies)!==JSON.stringify(base.dependencies)||JSON.stringify(s.toolIds)!==JSON.stringify(base.toolIds)||!!s.toolLane!==!!base.toolLane||!!s.stoveLane!==!!base.stoveLane)fail('步骤或时长不可修改');for(const dep of base.dependencies)if(!byId.has(dep)||byId.get(dep).end>s.start)fail('步骤依赖冲突');if(s.toolLane){const [id,n]=s.toolLane.split('#'),tool=state.kitchen.tools.find(t=>t.id===id&&t.available);if(!tool||!Number.isInteger(Number(n))||Number(n)<1||Number(n)>tool.quantity||!base.toolIds.includes(id)&&base.phase!=='finish')fail('锅具数量冲突');}if(s.stoveLane&&(!/^stove#[1-4]$/.test(s.stoveLane)||Number(s.stoveLane.split('#')[1])>state.kitchen.stoveSlots))fail('灶位冲突');}
 for(const a of plan.atomicTimeline)for(const b of plan.atomicTimeline){if(a.id>=b.id||!overlap(a,b))continue;if(a.handsOn&&b.handsOn||a.toolLane&&a.toolLane===b.toolLane||a.stoveLane&&a.stoveLane===b.stoveLane)fail('烹饪资源冲突');}
 for(const r of state.meal.selectedRecipeIds){for(const phases of [['heat','finish'],['appliance_setup','appliance'],['prep']]){const group=plan.atomicTimeline.filter(s=>s.recipeId===r&&phases.includes(s.phase)).sort((a,b)=>a.start-b.start);for(let i=1;i<group.length;i++)if(group[i].start!==group[i-1].end||group[i].toolLane!==group[i-1].toolLane||group[i].stoveLane!==group[i-1].stoveLane)fail('锅具占用或安全处理不可中断');}}
 const end=Math.max(...plan.atomicTimeline.map(s=>s.end));if(plan.optimizedMinutes!==end||plan.estimatedTotalMinutes!==end||plan.sequentialMinutes!==canonical.sequentialMinutes||plan.savedMinutes!==plan.sequentialMinutes-end)fail('节省时间不可伪造');
 const points=[...new Set(plan.atomicTimeline.flatMap(s=>[s.start,s.end]))].sort((a,b)=>a-b),windows=[];for(let i=0;i<points.length-1;i++){const start=points[i],end=points[i+1],steps=plan.atomicTimeline.filter(s=>s.start<=start&&s.end>=end);if(new Set(steps.map(s=>s.recipeId)).size>1)windows.push({start,end,stepIds:steps.map(s=>s.id)});}if(JSON.stringify(plan.parallelWindows)!==JSON.stringify(windows))fail('并行时间不可伪造');return plan;
}
